### ISSUE TITLE
hdfs feature fails to compile in rust-v0.16.0 and main

### ISSUE THREAD

**Issue by tlovell-sxt** [delta-io/delta-rs#1793]
# Environment

**Delta-rs version**: v0.16.0 up to main

**Binding**: rust

**Environment**:
- **Cloud provider**:
- **OS**: Pop!_OS
- **Other**:

***
# Bug

**What happened**:
Running `cargo check --features hdfs` fails with the following message:
```
error[E0277]: the trait bound `HadoopFileSystem: ObjectStore` is not satisfied
   --> rust/src/storage/config.rs:278:32
    |
278 |             url_prefix_handler(store, _prefix)
    |             ------------------ ^^^^^ the trait `ObjectStore` is not implemented for `HadoopFileSystem`
    |             |
    |             required by a bound introduced by this call
    |
    = help: the following other types implement trait `ObjectStore`:
              Box<(dyn ObjectStore + 'static)>
              ChunkedStore
              LimitStore<T>
              LocalFileSystem
              InMemory
              PrefixStore<T>
              ThrottledStore<T>
              FileStorageBackend
            and 2 others
note: required by a bound in `url_prefix_handler`
   --> rust/src/storage/config.rs:292:26
    |
292 | fn url_prefix_handler<T: ObjectStore>(store: T, prefix: Path) -> DeltaResult<Arc<DynObjectStore>> {
    |                          ^^^^^^^^^^^ required by this bound in `url_prefix_handler`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `deltalake` (lib) due to previous error
```

**What you expected to happen**:
The check should pass with this feature enabled.

**How to reproduce it**:
Run `cargo check --features hdfs`

**More details**:
It seems that `datafusion-objectstore-hdfs` has still not upgraded to `object_store` version `0.7`. I think that dependency probably just needs to be upgraded. However, it might be worth adding a check w/ this feature enabled in the CI in this repo to catch issues like this in the future.

**Comment by roeap** [comment]
this likely just needs to be fixed upstream. we are on version 0.7 of object store, which the upstream crate does not yet support - as such, the trait mentioned in the error message is in fact a different one :).

**Comment by rtyler** [comment]
@tlovell-sxt I have some changes working through the codebase right now to actually remove HDFS support from deltalake-core so that it can be put into a `deltalake-hdfs` crate. Would you be interested in working on that?

**Comment by Silemo** [comment]
Hi there!

Young developer here. As part of a larger project I am currently working on I want need delta-rs to have support for hdfs. I am currently looking at the repository you used in the past for hdfs support (https://github.com/datafusion-contrib/datafusion-objectstore-hdfs). I am continuing the conversation to gather some suggestion on how to actually proceed with the hdfs support.

As I am a young developer, I have a limited idea of which best practices and design choices are better suited for this task and I could use some help. Furthermore I could benefit from the feedback of someone that has contributed directly to the object_store crate.

Here's a list of question that might help me get started, feel free to add any comment or recommendation:

* When contributing to such a large change (more than 70 lines change) you still recommend a single PR? How should I prepare the work for the contribution?
* Do you have a schema or more detailed interface that you typically use for adding a storage crate? I have seen the other storage crates, but having a standardised interface to look at would be helpful. 
* Is there something in particular I should keep in mind when implementing for hdfs or contributing to this repo?

Thanks in advance for your response
