### ISSUE TITLE
[Bug]: polars.DataFrame.write_delta() failing for unknown argument 'schema'

### ISSUE THREAD

**Issue by beschmitt** [delta-io/delta-rs#4157]
### What happened?

I have tried running the example for writing a delta-table from a polars Dataframe found [here](https://delta-io.github.io/delta-rs/usage/create-delta-lake-table/).  
I need to give my Polars Dataframe an explicit schema to guarantee schema-matching. After trying to write my data as delta I got the following exception:  
`TypeError: write_deltalake() got an unexpected keyword argument 'schema'`  

I then removed the schema and even copied the example code one-to-one but I still got the exception.

### Expected behavior

Expected behaviour would that my data is written as a Delta-Table with the correct schema

### Operating System

Windows

### Binding

Python

### Bindings Version

1.4.1

### Steps to reproduce

1. Copy the example code from [here](https://delta-io.github.io/delta-rs/usage/create-delta-lake-table/)
2. Run it

### Relevant logs

```shell
File "...\deltalake_poc.py", line 40, in main
    df.write_delta("tmp/some-table")
  File "...\.venv\Lib\site-packages\polars\dataframe\frame.py", line 4607, in write_delta
    write_deltalake(
TypeError: write_deltalake() got an unexpected keyword argument 'schema'
```

**Comment by ethan-tyler** [comment]
What Polars version are you on? Some Polars versions always forward a `schema=` kwarg to `deltalake.write_deltalake()` (even `None`), but delta-rs 1.x doesn't accept `schema`. You might need to upgrade Polars to a compatible version or pin `deltalake<1.0`.

**Comment by beschmitt** [comment]
I am running polars 1.30.0. If this is a bug with newer versions of polars and it only works with version pre 1.0, then I'll just stick with pyarrow for now since that works just fine.

**Comment by ion-elgreco** [comment]
Polars became compatible with deltalake 1.x in their version 1.31.0

**Comment by ion-elgreco** [comment]
Polars became compatible with deltalake 1.x in their version 1.31.0
